apiVersion: v1
kind: Secret
metadata:
  name: milvus-ldap-sync
  namespace: milvus
type: Opaque
stringData:
  LDAP_BIND_PASSWORD: "admin"
  MILVUS_ROOT_PASSWORD: "user"
  MILVUS_SYNC_DEFAULT_PASSWORD: "AttuTest1"
